layout('site/layout.html.erb')

ignore('README.md')
ignore(/misc/)
ignore(/psd/)
ignore('site/css/animated_circle.css.sass')
ignore('site/css/color_content.css.sass')
ignore('site/css/experience.css.sass')
ignore('site/css/header.css.sass')
ignore('site/css/index.css.sass')
ignore('site/css/recent_content.css.sass')
ignore('site/css/variables.css.sass')
ignore('site/css/vector_graphic.css.sass')
ignore(/.sass-cache/)