layout('layout.html.erb')

ignore('README.md')
ignore('.gitignore')
ignore(/misc/)
ignore(/psd/)
ignore('css/animated_circle.css.sass')
ignore('css/color_content.css.sass')
ignore('css/experience.css.sass')
ignore('css/header.css.sass')
ignore('css/index.css.sass')
ignore('css/recent_content.css.sass')
ignore('css/variables.css.sass')
ignore('css/vector_graphic.css.sass')
ignore('css/menu.css.sass')
ignore('css/contact.css.sass')
ignore(/.sass-cache/)